### ISSUE TITLE
lr decay

### ISSUE THREAD

**Issue by wenhankang** [twni2016/Elastic-Boundary-Projection#10]
Why is this part of the training process stopped?Thank you for your attention
![image](https://user-images.githubusercontent.com/75669257/110265656-0b68cf80-7ff7-11eb-90eb-7bfbff9d85dd.png)

**Comment by wenhankang** [comment]
This is the other dataset used for training.

**Comment by wenhankang** [comment]
Occasionally I had Ir decay in the epoch1 when I finished training and restarted.

**Comment by twni2016** [comment]
This is quite weird. What's the error message? Just time out?

**Comment by wenhankang** [comment]
> 这很奇怪。错误消息是什么？只是超时？

It could be due to data generation problems when I use my own dataset.Just do it over again.I am glad to receive your reply
