### ISSUE TITLE
DSC-Average

### ISSUE THREAD

**Issue by wenhankang** [twni2016/Elastic-Boundary-Projection#11]
![image](https://user-images.githubusercontent.com/75669257/116497331-a5ebdd80-a8d9-11eb-8bb6-c7ccf3758158.png)
I'm sorry to bother you, but I would like to ask what is the meaning of +-4.50 in DSC-average.Any answer would be greatly appreciated

**Comment by twni2016** [comment]
Hi, this is the standard deviation among the DSCs of testing samples.
