### ISSUE TITLE
A problem about interp3 in data_generation

### ISSUE THREAD

**Issue by guolihong** [twni2016/Elastic-Boundary-Projection#3]
Hello,may I ask what does 
"(1-da) * ((1-db) * (Data[floor_a,floor_b,floor_c] * (1-dc) + \
								Data[floor_a,floor_b,floor_c+1] * (dc)) + \
						(db)   * (Data[floor_a,floor_b+1,floor_c] * (1-dc) + \
								Data[floor_a,floor_b+1,floor_c+1] * (dc))) + \
				(da)  * ((1-db) * (Data[floor_a+1,floor_b,floor_c] * (1-dc) + \
								Data[floor_a+1,floor_b,floor_c+1] * (dc)) + \
						(db)   * (Data[floor_a+1,floor_b+1,floor_c] * (1-dc) + \
								Data[floor_a+1,floor_b+1,floor_c+1] * (dc)))"
 mean?
Why not use Data[floor_a,floor_b,floor_c] directly?

**Comment by twni2016** [comment]
We use trilinear interpolation because `(floor_a, floor_b, floor_c)` is an underestimate of the actual point.
