### ISSUE TITLE
A question about "torch.cat((torch.from_numpy(X), self.direction,torch.from_numpy(X_in), self.direction))"

### ISSUE THREAD

**Issue by guolihong** [twni2016/Elastic-Boundary-Projection#4]
Hello!Why did you concat (X,direction,X_in,direction) instead of (X,X_in)?What is the role of direction?I'm looking forward your answer.Thank you!

**Comment by twni2016** [comment]
We add `direction` (spherical unit vectors) to the input because we hope the deep network will implicitly learn the geometric attributes of X, which is a 2D image map of a 3D shell.

**Comment by guolihong** [comment]
> We add direction (spherical unit vectors) to the input because we hope the deep network will implicitly learn the geometric attributes of X, which is a 2D image map of a 3D shell.

Thank you for your reply.
