### ISSUE TITLE
FileNotFoundError Problem

### ISSUE THREAD

**Issue by jcfszxc** [twni2016/Elastic-Boundary-Projection#5]
Hello, I met a problem when I was testing:

![image](https://user-images.githubusercontent.com/46143477/67140610-cbcd0680-f28e-11e9-94d8-252c3700d3bd.png)

I couldn't find where to generate xxx_pivot_list.npy and xxx.pkl to this path.

Could you give me some advice?

**Comment by twni2016** [comment]
Could you check where the model `xxx.pkl` is? It should be saved in that directory if you run `vnetg.py`. After you run `test_iter.py` successfully, you will get `xxx_pivot_list.npy` to run `test_voxel.py`.

**Comment by jcfszxc** [comment]
Thank you for your help, I have learned a lot from reading your paper.😊😊😊


| |
张翔辰
|
|
jcfszxc@126.com
|
签名由网易邮箱大师定制
On 10/30/2019 03:24，Tianwei Ni<notifications@github.com> wrote：

Closed #5.
