### ISSUE TITLE
Some question about testing

### ISSUE THREAD

**Issue by lizixia18** [twni2016/Elastic-Boundary-Projection#6]
Hi! I have two questions about testing. 
1、How to get bbox_info() without label in testing?
2、If the model is good trained,every pivot can get a shell.Why can't use the ending points of one pivot instead of  using the ending points of almost 3400 pivots to 3D reconstruction?
I'm looking forward your answer.Thank you!

**Comment by twni2016** [comment]
1. Actually, we need 3D ground-truth ROI calculated by a label in testing. 
2. Even if the model is ground-truth, one shell cannot recover all the boundaries because of occlusion and precision. We need many pivots sampled densely in ROI to avoid this issue.

**Comment by lizixia18** [comment]
Hi!
Is the accuray on three approaches  in your paper also obtained through the ROI generated by groundtruth?  If not, which approach you used?
I'm looking forward your answer.Thank you!
